version: "3"
services:
  app-1:
    build: ./example
    environment:
      - APP_NAME=App 1
  app-2:
    build: ./example
    environment:
      - APP_NAME=App 2
  app-3:
    build: ./example
    environment:
      - APP_NAME=App 3
  nginx:
    build: .
    ports:
      - 9000:80
    # volumes:
    # - ./templates/nginx.conf:/etc/nginx/nginx.conf:ro
